import type { Metadata } from 'next';
import { inter } from '@/lib/fonts';
import './globals.css';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className='' lang='en'>
			<body
				className={cn(
					'min-h-screen font-sans grainy antialiased',
					inter.className
				)}
			>
				{children}
			</body>
		</html>
	);
}
